### ISSUE TITLE
Security Violation - Access denied (403) - kleinanzeigen

### ISSUE THREAD

**Issue by simontree** [luimui/WG-Gesucht-Immoscout24-Ebay-Kleinanzeigen-Crawler#5]

**Comment by simontree** [comment]
.

**Comment by luimui** [comment]
Hi Robert,

Nice to hear you make use of the Script. I am at my unless birthday right
now, but I shall take a Look at it tomorrow.

Take care,
Lui

Am Donnerstag, 14. April 2022 schrieb Robert ***@***.***>:
> Hey, just tried to do a get request with your scraper.py but I only get
"Security Violation - Access denied (403)".
> It's probably due to the fact that you built your code three years ago &
now they implemented new security features.
> Not sure if there is a way around.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.<
https://ci5.googleusercontent.com/proxy/kIP9-lCOasbGycwhwhCnrDmQmGhdLLmiQglk0VylQDV01HOQ1YHYdR0E3Awdac1id160aFC6hnnYQGJJYz1CoPEfciQsXu0dUP0vrS-9XXemPo024Gs7MZW-DaGcAqBQJnDcPUv1_51_5cBhBtnW_ukfZUVs4_29zOvgLqs1_kcCWRIyd6q8M2K1Q8G8LnJWQHPkhcBKUQ23El700ehqBnRfsZw=s0-d-e1-ft#https://github.com/notifications/beacon/AIQW7OIMSKM7ZVCJMKBRKBDVFBD7RA5CNFSM5TOKE3J2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4R6PGE3Q.gif>Message
ID: <luimui/WG-Gesucht-Immoscout24-Ebay-Kleinanzeigen-Crawler/issues/
***@***.***>

**Comment by simontree** [comment]
Hi Lui,
thanks for your reply.
Solved it already with spoofing a user-agent for kleinanzeigen & now it works! 
Thanks anyway! :)


Oct 11, 2022, 09:40 by ***@***.***:
